In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

In [3]:
iris = load_iris()
values = iris.data
target = iris.target
ss = StandardScaler()
values = ss.fit_transform(values)
x_train, x_test, y_train, y_test = train_test_split(values, target, test_size = 0.3, random_state = 1)
n = 1000
loss_cur = 999
classifier = MLPClassifier(hidden_layer_sizes = (4,3), activation = 'logistic', solver = 'sgd',learning_rate_init = 0.5, warm_start = True,  random_state = 1,max_iter = 1, verbose = True)

for _ in range(n):
    classifier.fit(x_train, y_train)
    loss_prev = loss_cur
    loss_cur = classifier.loss_
    for i in classifier.coefs_:
        print(i, end='\n\n')
    if(abs(loss_cur - loss_prev)<0.0001):
        break
pred = classifier.predict(x_test)

Iteration 1, loss = 1.37415394
[[-0.06830242  0.22960692 -0.51269239 -0.20269188]
 [-0.36260071 -0.40906024 -0.30746402 -0.15261128]
 [-0.08548541  0.04924238 -0.09633806  0.17942759]
 [-0.27807308  0.38904888 -0.48848345  0.16458452]]

[[ 0.30029384  0.45819188 -0.20805575]
 [ 0.19694935  0.3859567   0.41162911]
 [-0.468751   -0.54342141 -0.35971464]
 [ 0.39235615 -0.4527608  -0.09156645]]

[[-0.06666138  0.26974618  0.18563581]
 [-0.44480663  0.33148934  0.41041418]
 [ 0.39598025 -0.21075333  0.18183932]]

Iteration 2, loss = 1.14637672
[[-0.05782259  0.23404034 -0.5200728  -0.20787054]
 [-0.3705537  -0.41009599 -0.30225469 -0.15037559]
 [-0.07253802  0.05442774 -0.10580615  0.17329872]
 [-0.26556293  0.39445932 -0.49794251  0.15838568]]

[[ 0.29479352  0.43985284 -0.20324603]
 [ 0.19743242  0.38803843  0.40985429]
 [-0.47725714 -0.57161686 -0.35114384]
 [ 0.39008477 -0.45959953 -0.08964465]]

[[ 0.0114439   0.25452397  0.12275239]
 [-0.39037485  0.32086109  0.36661038]
 [ 0.45274058

C:\Users\Aditya\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1) reached and the optimization hasn't converged yet.
  warnings.warn(


Iteration 85, loss = 0.48608429
[[ 0.52048755  0.58666495 -0.81321998 -0.61783252]
 [-0.86421485 -0.78929856  0.4110752   0.17164417]
 [ 0.80254629  0.70311519 -0.81594364 -0.4512226 ]
 [ 0.62304912  1.07317998 -1.2145771  -0.4942773 ]]

[[ 0.5950204   1.46271574 -0.83028926]
 [ 0.61455466  2.09549553 -0.44313056]
 [-1.11230301 -2.37592609  0.59705273]
 [ 0.03598814 -1.10801649  0.3654737 ]]

[[-0.62072222  0.47017269  0.5392406 ]
 [-3.47680873  1.11942298  2.65446005]
 [ 1.41168506 -0.32401869 -0.72062804]]

Iteration 86, loss = 0.48388637
[[ 0.5208453   0.58551705 -0.81126296 -0.61851455]
 [-0.86515308 -0.79028814  0.41272673  0.17235494]
 [ 0.8057472   0.70466193 -0.81711079 -0.45402456]
 [ 0.62737061  1.07572912 -1.21674801 -0.49793397]]

[[ 0.59914452  1.46525792 -0.83907431]
 [ 0.61897213  2.09829096 -0.45258959]
 [-1.11842226 -2.38251035  0.60671451]
 [ 0.03133279 -1.11373816  0.37285265]]

[[-0.62957536  0.4710822   0.54718388]
 [-3.49712027  1.12264899  2.67154532]
 [ 1.424785

Iteration 176, loss = 0.29756177
[[ 0.13020831  0.02285998 -0.02553678 -0.32413914]
 [-0.75734722 -0.78420996  0.28714675 -0.05694383]
 [ 0.93315404  0.68936101 -0.69319423 -0.60143255]
 [ 1.00552444  1.28112044 -1.36142871 -0.86874923]]

[[ 0.99903759  1.54478503 -1.35477788]
 [ 1.03700357  2.19404456 -1.00029587]
 [-1.56189765 -2.68438415  1.45689746]
 [-0.322106   -1.39553795  1.17822647]]

[[-1.52076431  0.58232489  1.32709849]
 [-4.75016979  0.85516479  4.19205485]
 [ 2.24365527  0.50521401 -2.38186116]]

Iteration 177, loss = 0.29512787
[[ 0.12304086  0.01395294 -0.01145086 -0.31765282]
 [-0.75495301 -0.78391369  0.28218023 -0.0633658 ]
 [ 0.93430176  0.68966011 -0.69182616 -0.60285079]
 [ 1.0098575   1.28405125 -1.36402464 -0.8735868 ]]

[[ 1.00501593  1.54781002 -1.35989925]
 [ 1.04325065  2.19760606 -1.00541629]
 [-1.56651292 -2.68626521  1.46736477]
 [-0.32556521 -1.3963852   1.18886832]]

[[-1.53284786  0.58513782  1.33636876]
 [-4.76231091  0.84965084  4.20970964]
 [ 2.2516

Iteration 271, loss = 0.15446767
[[-0.10838458 -0.21432995  0.42601327 -0.10270765]
 [-0.86942467 -1.14683909 -0.12016759 -0.58294848]
 [ 1.06464679  0.8324727  -0.8746746  -0.83674509]
 [ 1.16320572  1.37569262 -1.55662498 -1.23217756]]

[[ 1.56954256  1.80226436 -1.80029173]
 [ 1.66074088  2.50986289 -1.37073158]
 [-1.86882097 -2.70223875  2.3334152 ]
 [-0.52883141 -1.35007134  2.14816697]]

[[-2.49896039  0.9881175   1.89946855]
 [-5.66041974  0.68054072  5.27690333]
 [ 2.98257349  1.2894801  -3.90507701]]

Iteration 272, loss = 0.15359104
[[-0.10860609 -0.21379648  0.42664477 -0.10220585]
 [-0.87326381 -1.15241014 -0.1229177  -0.58537232]
 [ 1.0658703   0.83399801 -0.87769418 -0.83996392]
 [ 1.16321308  1.37540059 -1.55799811 -1.23548417]]

[[ 1.57449409  1.80368015 -1.80450528]
 [ 1.66643398  2.51196708 -1.37396694]
 [-1.870765   -2.70185757  2.34099315]
 [-0.53002935 -1.34935257  2.15654546]]

[[-2.50668934  0.99237376  1.90294089]
 [-5.66718281  0.68058168  5.28362517]
 [ 2.9890

Iteration 368, loss = 0.10170633
[[-0.04802398 -0.08628576  0.46723768 -0.01427034]
 [-1.21483104 -1.54061193 -0.26350877 -0.61480627]
 [ 1.16454344  0.95604516 -1.15496146 -1.11292949]
 [ 1.12374481  1.3277629  -1.65472236 -1.46154997]]

[[ 1.93899462  1.89202445 -2.12570314]
 [ 2.08223213  2.64898859 -1.62410159]
 [-2.00772844 -2.67013304  2.91588811]
 [-0.62807197 -1.29530073  2.75128243]]

[[-3.07343321  1.33830415  2.12372062]
 [-6.14640557  0.71133361  5.7320702 ]
 [ 3.4658925   1.80529408 -4.90424221]]

Iteration 369, loss = 0.10138872
[[-0.04674829 -0.08447111  0.4675969  -0.0131169 ]
 [-1.21782437 -1.54330854 -0.26408068 -0.61397292]
 [ 1.1653779   0.95709991 -1.15755798 -1.11530392]
 [ 1.12304805  1.32714716 -1.65529708 -1.46298926]]

[[ 1.94186428  1.89266651 -2.12825549]
 [ 2.08544713  2.64997235 -1.62607794]
 [-2.00882416 -2.66980724  2.9205591 ]
 [-0.62897062 -1.29482073  2.75587829]]

[[-3.07793896  1.34124547  2.1252847 ]
 [-6.15011082  0.71175962  5.73534918]
 [ 3.4696

Iteration 463, loss = 0.08024599
[[ 0.10062514  0.09388006  0.49324721  0.08347022]
 [-1.46687277 -1.73526356 -0.29386151 -0.51515381]
 [ 1.22733669  1.03763238 -1.36759951 -1.30189082]
 [ 1.04357051  1.26108461 -1.67891421 -1.54419851]]

[[ 2.15938844  1.94129581 -2.32921326]
 [ 2.3272735   2.72291087 -1.77829175]
 [-2.09469411 -2.63758026  3.28304269]
 [-0.70175735 -1.25162877  3.11184392]]

[[-3.4249949   1.56796235  2.24559071]
 [-6.43275019  0.74852962  5.98119329]
 [ 3.75742447  2.15460077 -5.5451124 ]]

Iteration 464, loss = 0.08008444
[[ 0.10236971  0.09575716  0.49346168  0.08431973]
 [-1.46929607 -1.73686181 -0.29411175 -0.51407871]
 [ 1.22785711  1.03831722 -1.3694827  -1.30352476]
 [ 1.04265461  1.26032837 -1.678953   -1.54464879]]

[[ 2.1612684   1.94171441 -2.33109233]
 [ 2.32935861  2.72353111 -1.77968293]
 [-2.09546003 -2.63723241  3.28625605]
 [-0.70241111 -1.25118567  3.1150274 ]]

[[-3.42805095  1.56993091  2.24667784]
 [-6.43521942  0.74886775  5.98332413]
 [ 3.7599

Iteration 550, loss = 0.06894124
[[ 0.25394185  0.24758611  0.51403389  0.1444883 ]
 [-1.66754994 -1.8545232  -0.32543536 -0.43381757]
 [ 1.26788874  1.089034   -1.5075313  -1.42096502]
 [ 0.96967751  1.1978597  -1.67985829 -1.56884706]]

[[ 2.30055001  1.97200831 -2.48508209]
 [ 2.48477399  2.76886102 -1.89229376]
 [-2.15378127 -2.60893883  3.52834273]
 [-0.75092604 -1.21471645  3.35819744]]

[[-3.65774595  1.71629054  2.32998299]
 [-6.62001619  0.77490795  6.14205759]
 [ 3.94612469  2.41161864 -5.99085937]]

Iteration 551, loss = 0.06883736
[[ 0.25567362  0.24922059  0.51431917  0.14505487]
 [-1.66974986 -1.85569899 -0.32593684 -0.43304412]
 [ 1.26832228  1.08955284 -1.50888606 -1.42208553]
 [ 0.96893584  1.19719187 -1.67988821 -1.56902059]]

[[ 2.30194987  1.97230157 -2.48680728]
 [ 2.48635111  2.76930887 -1.89354086]
 [-2.1543905  -2.60863726  3.53081264]
 [-0.75141294 -1.21431413  3.36071702]]

[[-3.66008965  1.71777871  2.33083816]
 [-6.62189425  0.77518992  6.14365342]
 [ 3.9480

In [4]:
cm = confusion_matrix(y_test,pred)
print("Confusion Matrix",cm,sep="\n")
print("Accuracy", accuracy_score(y_test,pred))

Confusion Matrix
[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]
Accuracy 0.9555555555555556


In [5]:
for i in classifier.coefs_:
    print(i)

[[ 0.27118627  0.26378462  0.5169424   0.15003044]
 [-1.68944885 -1.86611421 -0.3305923  -0.42624367]
 [ 1.27220675  1.09416906 -1.52085131 -1.43194152]
 [ 0.96239605  1.19126248 -1.68020878 -1.57051609]]
[[ 2.31435723  1.97488769 -2.50227553]
 [ 2.50034857  2.77327085 -1.90470671]
 [-2.15982074 -2.60595851  3.55273073]
 [-0.75572826 -1.21071785  3.38311411]]
[[-3.68089591  1.7309991   2.33842088]
 [-6.63856087  0.77772009  6.15778743]
 [ 3.96489722  2.43840789 -6.03642447]]
